[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  command = "vite dev"
  targetPort = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/* /index.html 200"
  status = 200
  
